// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Automatically generate sidebar from docs folder
    },
    {
      type: 'link',
      label: '📬 Subscribe to Newsletter',
      href: 'https://mailer.nekonik.com/subscription/form',
    },
  ],
};

export default sidebars;
